// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: receipt.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a train ticket receipt.
type Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`                // Unique identifier for the ticket
	FromLocation  string                 `protobuf:"bytes,2,opt,name=from_location,json=fromLocation,proto3" json:"from_location,omitempty"`    // e.g., "London"
	ToLocation    string                 `protobuf:"bytes,3,opt,name=to_location,json=toLocation,proto3" json:"to_location,omitempty"`          // e.g., "France"
	User          *User                  `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`                                        // Reference to the User message
	PricePaid     float64                `protobuf:"fixed64,5,opt,name=price_paid,json=pricePaid,proto3" json:"price_paid,omitempty"`           // Price in USD, e.g., 20.00
	AllocatedSeat *Seat                  `protobuf:"bytes,6,opt,name=allocated_seat,json=allocatedSeat,proto3" json:"allocated_seat,omitempty"` // Reference to the Seat message
	PurchaseDate  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=purchase_date,json=purchaseDate,proto3" json:"purchase_date,omitempty"`    // Timestamp when the ticket was purchased
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_receipt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_receipt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_receipt_proto_rawDescGZIP(), []int{0}
}

func (x *Receipt) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *Receipt) GetFromLocation() string {
	if x != nil {
		return x.FromLocation
	}
	return ""
}

func (x *Receipt) GetToLocation() string {
	if x != nil {
		return x.ToLocation
	}
	return ""
}

func (x *Receipt) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Receipt) GetPricePaid() float64 {
	if x != nil {
		return x.PricePaid
	}
	return 0
}

func (x *Receipt) GetAllocatedSeat() *Seat {
	if x != nil {
		return x.AllocatedSeat
	}
	return nil
}

func (x *Receipt) GetPurchaseDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PurchaseDate
	}
	return nil
}

var File_receipt_proto protoreflect.FileDescriptor

const file_receipt_proto_rawDesc = "" +
	"\n" +
	"\rreceipt.proto\x12\x17trainticketing.entities\x1a\n" +
	"user.proto\x1a\n" +
	"seat.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x02\n" +
	"\aReceipt\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12#\n" +
	"\rfrom_location\x18\x02 \x01(\tR\ffromLocation\x12\x1f\n" +
	"\vto_location\x18\x03 \x01(\tR\n" +
	"toLocation\x121\n" +
	"\x04user\x18\x04 \x01(\v2\x1d.trainticketing.entities.UserR\x04user\x12\x1d\n" +
	"\n" +
	"price_paid\x18\x05 \x01(\x01R\tpricePaid\x12D\n" +
	"\x0eallocated_seat\x18\x06 \x01(\v2\x1d.trainticketing.entities.SeatR\rallocatedSeat\x12?\n" +
	"\rpurchase_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fpurchaseDateB/Z-github.com/talk2sohail/train-ticket-api/protob\x06proto3"

var (
	file_receipt_proto_rawDescOnce sync.Once
	file_receipt_proto_rawDescData []byte
)

func file_receipt_proto_rawDescGZIP() []byte {
	file_receipt_proto_rawDescOnce.Do(func() {
		file_receipt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_receipt_proto_rawDesc), len(file_receipt_proto_rawDesc)))
	})
	return file_receipt_proto_rawDescData
}

var file_receipt_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_receipt_proto_goTypes = []any{
	(*Receipt)(nil),               // 0: trainticketing.entities.Receipt
	(*User)(nil),                  // 1: trainticketing.entities.User
	(*Seat)(nil),                  // 2: trainticketing.entities.Seat
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_receipt_proto_depIdxs = []int32{
	1, // 0: trainticketing.entities.Receipt.user:type_name -> trainticketing.entities.User
	2, // 1: trainticketing.entities.Receipt.allocated_seat:type_name -> trainticketing.entities.Seat
	3, // 2: trainticketing.entities.Receipt.purchase_date:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_receipt_proto_init() }
func file_receipt_proto_init() {
	if File_receipt_proto != nil {
		return
	}
	file_user_proto_init()
	file_seat_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_receipt_proto_rawDesc), len(file_receipt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_receipt_proto_goTypes,
		DependencyIndexes: file_receipt_proto_depIdxs,
		MessageInfos:      file_receipt_proto_msgTypes,
	}.Build()
	File_receipt_proto = out.File
	file_receipt_proto_goTypes = nil
	file_receipt_proto_depIdxs = nil
}
