// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: seat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Seat_Section int32

const (
	Seat_SECTION_UNKNOWN Seat_Section = 0 // Default or unassigned section
	Seat_SECTION_A       Seat_Section = 1
	Seat_SECTION_B       Seat_Section = 2
)

// Enum value maps for Seat_Section.
var (
	Seat_Section_name = map[int32]string{
		0: "SECTION_UNKNOWN",
		1: "SECTION_A",
		2: "SECTION_B",
	}
	Seat_Section_value = map[string]int32{
		"SECTION_UNKNOWN": 0,
		"SECTION_A":       1,
		"SECTION_B":       2,
	}
)

func (x Seat_Section) Enum() *Seat_Section {
	p := new(Seat_Section)
	*p = x
	return p
}

func (x Seat_Section) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Seat_Section) Descriptor() protoreflect.EnumDescriptor {
	return file_seat_proto_enumTypes[0].Descriptor()
}

func (Seat_Section) Type() protoreflect.EnumType {
	return &file_seat_proto_enumTypes[0]
}

func (x Seat_Section) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Seat_Section.Descriptor instead.
func (Seat_Section) EnumDescriptor() ([]byte, []int) {
	return file_seat_proto_rawDescGZIP(), []int{0, 0}
}

// Represents a seat on the train.
type Seat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       Seat_Section           `protobuf:"varint,1,opt,name=section,proto3,enum=trainticketing.entities.Seat_Section" json:"section,omitempty"`
	SeatNumber    string                 `protobuf:"bytes,2,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"` // e.g., "1A", "1B", "2C"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_seat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_seat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_seat_proto_rawDescGZIP(), []int{0}
}

func (x *Seat) GetSection() Seat_Section {
	if x != nil {
		return x.Section
	}
	return Seat_SECTION_UNKNOWN
}

func (x *Seat) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

var File_seat_proto protoreflect.FileDescriptor

const file_seat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"seat.proto\x12\x17trainticketing.entities\"\xa6\x01\n" +
	"\x04Seat\x12?\n" +
	"\asection\x18\x01 \x01(\x0e2%.trainticketing.entities.Seat.SectionR\asection\x12\x1f\n" +
	"\vseat_number\x18\x02 \x01(\tR\n" +
	"seatNumber\"<\n" +
	"\aSection\x12\x13\n" +
	"\x0fSECTION_UNKNOWN\x10\x00\x12\r\n" +
	"\tSECTION_A\x10\x01\x12\r\n" +
	"\tSECTION_B\x10\x02B/Z-github.com/talk2sohail/train-ticket-api/protob\x06proto3"

var (
	file_seat_proto_rawDescOnce sync.Once
	file_seat_proto_rawDescData []byte
)

func file_seat_proto_rawDescGZIP() []byte {
	file_seat_proto_rawDescOnce.Do(func() {
		file_seat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seat_proto_rawDesc), len(file_seat_proto_rawDesc)))
	})
	return file_seat_proto_rawDescData
}

var file_seat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_seat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_seat_proto_goTypes = []any{
	(Seat_Section)(0), // 0: trainticketing.entities.Seat.Section
	(*Seat)(nil),      // 1: trainticketing.entities.Seat
}
var file_seat_proto_depIdxs = []int32{
	0, // 0: trainticketing.entities.Seat.section:type_name -> trainticketing.entities.Seat.Section
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_seat_proto_init() }
func file_seat_proto_init() {
	if File_seat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seat_proto_rawDesc), len(file_seat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_seat_proto_goTypes,
		DependencyIndexes: file_seat_proto_depIdxs,
		EnumInfos:         file_seat_proto_enumTypes,
		MessageInfos:      file_seat_proto_msgTypes,
	}.Build()
	File_seat_proto = out.File
	file_seat_proto_goTypes = nil
	file_seat_proto_depIdxs = nil
}
